/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedFieldIdRouteImport } from './routes/_authenticated/field.$id'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/_authenticated/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/_authenticated/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFieldIdRoute = AuthenticatedFieldIdRouteImport.update({
  id: '/_authenticated/field/$id',
  path: '/field/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/_authenticated/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/_authenticated/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reports': typeof AuthenticatedReportsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
  '/field/$id': typeof AuthenticatedFieldIdRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/reports': typeof AuthenticatedReportsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
  '/field/$id': typeof AuthenticatedFieldIdRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/field/$id': typeof AuthenticatedFieldIdRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reports'
    | '/sites'
    | '/team'
    | '/'
    | '/field/$id'
    | '/tasks/$id'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reports'
    | '/sites'
    | '/team'
    | '/'
    | '/field/$id'
    | '/tasks/$id'
    | '/tasks'
  id:
    | '__root__'
    | '/_authenticated/reports'
    | '/_authenticated/sites'
    | '/_authenticated/team'
    | '/_authenticated/'
    | '/_authenticated/field/$id'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFieldIdRoute: typeof AuthenticatedFieldIdRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/field/$id': {
      id: '/_authenticated/field/$id'
      path: '/field/$id'
      fullPath: '/field/$id'
      preLoaderRoute: typeof AuthenticatedFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFieldIdRoute: AuthenticatedFieldIdRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
